/*
 *  Copyright 2009 Eko Kurniawan Khannedy.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * DialogKaryawan.java
 *
 * Created on 10 Feb 09, 11:58:48
 */
package com.pos.spatobiz.app.view.karyawan;

import com.pos.spatobiz.app.util.SpringUtilities;
import com.pos.spatobiz.app.view.ButtonCrud;
import com.pos.spatobiz.common.dao.KaryawanDao;
import com.pos.spatobiz.common.entity.Karyawan;
import com.pos.spatobiz.common.error.SpatoBizException;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author echo
 */
public class DialogKaryawan extends javax.swing.JDialog {

    private Frame application;

    /** Creates new form DialogKaryawan */
    public DialogKaryawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        application = parent;

        buttonCrud1.getButtonTambah().addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                DialogKaryawanCrud crud = new DialogKaryawanCrud(application, true);
                crud.setLocationRelativeTo(DialogKaryawan.this);
                try {
                    Karyawan karyawan = crud.startDialog(null);
                    if (karyawan != null) {
                        KaryawanDao dao = (KaryawanDao) SpringUtilities.getApplicationContext().getBean("karyawanDao");
                        dao.insertKaryawan(karyawan);
                        panelTableKaryawan1.getTableModelKaryawan().addKaryawan(karyawan);
                    }
                } catch (SpatoBizException sbe) {
                    JOptionPane.showMessageDialog(DialogKaryawan.this, sbe.getMessage());
                } finally {
                    crud.dispose();
                }
            }
        });
    }

    public void startDialog() throws SpatoBizException {
        KaryawanDao dao = (KaryawanDao) SpringUtilities.getApplicationContext().getBean("karyawanDao");
        panelTableKaryawan1.getTableModelKaryawan().setKaryawans(dao.selectKaryawan());
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTableKaryawan1 = new PanelTableKaryawan();
        buttonCrud1 = new ButtonCrud();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Karyawan");
        getContentPane().add(panelTableKaryawan1, BorderLayout.CENTER);
        getContentPane().add(buttonCrud1, BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogKaryawan dialog = new DialogKaryawan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected ButtonCrud buttonCrud1;
    protected PanelTableKaryawan panelTableKaryawan1;
    // End of variables declaration//GEN-END:variables
}
