/*
 *  Copyright 2009 Eko Kurniawan Khannedy.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */
package com.pos.spatobiz.app.view.karyawan;

import com.pos.spatobiz.app.controller.karyawan.TampilkanTambahKaryawanAction;
import com.pos.spatobiz.app.view.widget.BigButton;
import echo.gokil.desktop.swing.Panel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.Locale;
import javax.swing.ImageIcon;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

/**
 *
 * @author echo
 */
public class MenuKaryawan extends Panel implements ApplicationContextAware, InitializingBean {

    private static final long serialVersionUID = 1L;

    private ApplicationContext applicationContext;

    private TampilkanTambahKaryawanAction tampilkanTambahKaryawanAction;

    /** Creates new form MenuKaryawan */
    public MenuKaryawan() {
        initComponents();
    }

    public TampilkanTambahKaryawanAction getTampilkanTambahKaryawanAction() {
        return tampilkanTambahKaryawanAction;
    }

    public void setTampilkanTambahKaryawanAction(TampilkanTambahKaryawanAction tampilkanTambahKaryawanAction) {
        this.tampilkanTambahKaryawanAction = tampilkanTambahKaryawanAction;
        getButtonTambahKaryawan().addActionListener(tampilkanTambahKaryawanAction);
    }

    public BigButton getButtonDataKaryawan() {
        return buttonDataKaryawan;
    }

    public BigButton getButtonEditKaryawan() {
        return buttonEditKaryawan;
    }

    public BigButton getButtonTambahKaryawan() {
        return buttonTambahKaryawan;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonDataKaryawan = new BigButton();
        buttonTambahKaryawan = new BigButton();
        buttonEditKaryawan = new BigButton();
        buttonHapusKaryawan = new BigButton();

        setLayout(new GridBagLayout());

        buttonDataKaryawan.setIcon(new ImageIcon(getClass().getResource("/com/pos/spatobiz/app/resource/image/karyawan/karyawan.png"))); // NOI18N
        buttonDataKaryawan.setText("Data Karyawan");
        add(buttonDataKaryawan, new GridBagConstraints());

        buttonTambahKaryawan.setIcon(new ImageIcon(getClass().getResource("/com/pos/spatobiz/app/resource/image/karyawan/tambah.png"))); // NOI18N
        buttonTambahKaryawan.setText("Tambah Karyawan");
        add(buttonTambahKaryawan, new GridBagConstraints());

        buttonEditKaryawan.setText("Ubah Karyawan");
        add(buttonEditKaryawan, new GridBagConstraints());

        buttonHapusKaryawan.setText("Hapus Karyawan");
        add(buttonHapusKaryawan, new GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }

    public void afterPropertiesSet() throws Exception {
        setTitle(applicationContext.getMessage("menukaryawan.title", null, Locale.getDefault()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected BigButton buttonDataKaryawan;
    protected BigButton buttonEditKaryawan;
    protected BigButton buttonHapusKaryawan;
    protected BigButton buttonTambahKaryawan;
    // End of variables declaration//GEN-END:variables
}
