/*
 *  Copyright 2009 Eko Kurniawan Khannedy.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */
package com.pos.spatobiz.app.view.karyawan;

import com.pos.spatobiz.common.entity.Karyawan;
import com.pos.spatobiz.common.error.SpatoBizException;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author echo
 */
public class PanelKaryawanCrud extends javax.swing.JPanel implements ActionListener {

    private static final long serialVersionUID = 1L;

    /** Creates new form PanelKaryawanCrud */
    public PanelKaryawanCrud() {
        initComponents();
        fileChooser.setFileFilter(new FileFilter() {

            private String description = "Image File (JPG/PNG)";

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                String name = f.getName().toLowerCase();
                if (name.endsWith(".jpg")) {
                    return true;
                } else if (name.endsWith(".png")) {
                    return true;
                } else {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return description;
            }
        });
    }

    public Karyawan getKaryawan() throws SpatoBizException {
        if (textAlamat.getText().isEmpty() || textEmail.getText().isEmpty() || textKode.getText().isEmpty() || textNama.getText().isEmpty() || textTelepon.getText().isEmpty() || labelPhoto.getIcon() == null) {
            throw new SpatoBizException("data harus lengkap");
        }
        Karyawan karyawan = new Karyawan();
        karyawan.setNama(textNama.getText());
        karyawan.setAlamat(textAlamat.getText());
        karyawan.setEmail(textEmail.getText());
        karyawan.setKode(textKode.getText());
        karyawan.setPhoto((ImageIcon) labelPhoto.getIcon());
        karyawan.setTanggalLahir((Date) textTanggalLahir.getValue());
        karyawan.setTelepon(textTelepon.getText());
        return karyawan;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new JFileChooser();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        textKode = new JTextField();
        textNama = new JTextField();
        textTanggalLahir = new JFormattedTextField();
        textTelepon = new JTextField();
        textEmail = new JTextField();
        jScrollPane1 = new JScrollPane();
        textAlamat = new JTextArea();
        buttonBukaPhoto = new JButton();
        jScrollPane2 = new JScrollPane();
        labelPhoto = new JLabel();

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("Tahoma", 1, 18));
        jLabel1.setText("Karyawan");

        jLabel2.setText("Silahkan isi data karyawan lalu tekan Ok");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        jLabel3.setText("Kode");

        jLabel4.setText("Nama");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Telepon");

        jLabel7.setText("Email");

        jLabel8.setText("Alamat");

        jLabel9.setText("Photo");

        textTanggalLahir.setFormatterFactory(new DefaultFormatterFactory(new DateFormatter(DateFormat.getDateInstance(DateFormat.LONG))));
        textTanggalLahir.setValue(new Date());

        textAlamat.setColumns(20);
        textAlamat.setRows(5);
        jScrollPane1.setViewportView(textAlamat);

        buttonBukaPhoto.setText("Buka File");
        buttonBukaPhoto.addActionListener(this);

        labelPhoto.setHorizontalAlignment(SwingConstants.CENTER);
        jScrollPane2.setViewportView(labelPhoto);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(textEmail, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(textTelepon, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(textNama, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(textTanggalLahir, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(textKode, GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonBukaPhoto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textKode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNama, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textTanggalLahir, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textTelepon, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(buttonBukaPhoto))
                .addContainerGap())
        );
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == buttonBukaPhoto) {
            PanelKaryawanCrud.this.buttonBukaPhotoActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBukaPhotoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_buttonBukaPhotoActionPerformed
        // TODO add your handling code here:
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(file.toURI().toURL());
                labelPhoto.setIcon(icon);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonBukaPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected JButton buttonBukaPhoto;
    protected JFileChooser fileChooser;
    protected JLabel jLabel1;
    protected JLabel jLabel2;
    protected JLabel jLabel3;
    protected JLabel jLabel4;
    protected JLabel jLabel5;
    protected JLabel jLabel6;
    protected JLabel jLabel7;
    protected JLabel jLabel8;
    protected JLabel jLabel9;
    protected JPanel jPanel1;
    protected JScrollPane jScrollPane1;
    protected JScrollPane jScrollPane2;
    protected JLabel labelPhoto;
    protected JTextArea textAlamat;
    protected JTextField textEmail;
    protected JTextField textKode;
    protected JTextField textNama;
    protected JFormattedTextField textTanggalLahir;
    protected JTextField textTelepon;
    // End of variables declaration//GEN-END:variables
}
