/*
 *  Copyright 2009 Eko Kurniawan Khannedy.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * ImageChooser.java
 *
 * Created on 11 Feb 09, 14:21:37
 */

package com.pos.spatobiz.app.view.widget;

import echo.gokil.desktop.swing.Button;
import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author echo
 */
public class ImageChooser extends javax.swing.JPanel {

    /** Creates new form ImageChooser */
    public ImageChooser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneLabel = new JScrollPane();
        labelIcon = new JLabel();
        buttonOpen = new Button();

        setOpaque(false);

        scrollPaneLabel.setName("scrollPaneLabel"); // NOI18N

        labelIcon.setBackground(new Color(255, 255, 255));
        labelIcon.setName("labelIcon"); // NOI18N
        labelIcon.setOpaque(true);
        scrollPaneLabel.setViewportView(labelIcon);

        buttonOpen.setMnemonic('C');
        buttonOpen.setText("Cari");
        buttonOpen.setName("buttonOpen"); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollPaneLabel, GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(buttonOpen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonOpen, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(scrollPaneLabel, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected Button buttonOpen;
    protected JLabel labelIcon;
    protected JScrollPane scrollPaneLabel;
    // End of variables declaration//GEN-END:variables

}
