/*
 *  Copyright 2009 Eko Kurniawan Khannedy.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * ButtonStandard.java
 *
 * Created on 10 Feb 09, 11:53:08
 */
package com.pos.spatobiz.app.view;

import javax.swing.JButton;

/**
 *
 * @author echo
 */
public class ButtonStandard extends javax.swing.JPanel {

    /** Creates new form ButtonStandard */
    public ButtonStandard() {
        initComponents();
    }

    public JButton getButtonBatal() {
        return buttonBatal;
    }

    public JButton getButtonOK() {
        return buttonOK;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOK = new JButton();
        buttonBatal = new JButton();

        buttonOK.setText("Ok");
        add(buttonOK);

        buttonBatal.setText("Batal");
        add(buttonBatal);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected JButton buttonBatal;
    protected JButton buttonOK;
    // End of variables declaration//GEN-END:variables
}
